version: '3'
services:
  lsst_stack:
    image: huntsmanarray/lsst:latest
    user: root
    stdin_open: true
    tty: true
    volumes:
      - "$OBS_HUNTSMAN:/opt/lsst/software/stack/stack/current/Linux64/obs_huntsman"
      - "$OBS_HUNTSMAN_TESTDATA:/opt/lsst/software/stack/testdata"
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/stack/current/Linux64/obs_huntsman
  lsst_firefly:
    image: ipac/firefly:lsst-dev
    ports:
      - "8080:8080"
    environment:
      - "MAX_JVM_SIZE=8G"
